import streamlit as st
from helper_functions import *
from chatbot import generate_chat_completion

# Set app icon and title
st.set_page_config(page_title="AI-Powered CV Advisor", page_icon="📄", layout="wide", 
                   menu_items=
                   {
                        'Get Help': 'https://www.extremelycoolapp.com/help',
                        'Report a bug': "https://www.extremelycoolapp.com/bug",
                        'About': "# This is a header. This is an *extremely* cool app!"
                    }
)

# Streamlit UI
st.title("AI-Powered CV Advisor")

# Create two columns
col1, col2 = st.columns([1, 1])  # Adjust ratios as needed

# Upper section in the first column
with col1:
    st.header("Upload your CV")
    uploaded_file = st.file_uploader("You can upload your current CV (PDF or DOCX)", type=["pdf", "docx"])

    # Display uploaded file information
    if uploaded_file is not None:
        st.success(f"File '{uploaded_file.name}' uploaded successfully!")

    # Additional Inputs
    st.subheader("Additional Information")
    with st.expander("Provide additional context (optional)"):
        job_url = st.text_input("Enter the job listing URL (LinkedIn, company website, etc.):")
        skills = st.text_input("List key skills relevant to the job (comma-separated):")
        experience = st.text_area("Describe your relevant experience:")    


    if uploaded_file:
        # st.subheader("Extracted Text:")
        cv_text = extract_text_from_file(uploaded_file)
        # st.text_area("CV Content", cv_text, height=300)

        # Initialize session state for advice and new CV text
        if 'advice_text' not in st.session_state:
            st.session_state.advice_text = ""
        if 'new_cv_text' not in st.session_state:
            st.session_state.new_cv_text = ""
        
        # if st.button("Analyze CV") or st.session_state.advice_text != "":
        #     # st.write("**AI Analysis & Recommendations Coming Soon...**")
        #     prompt = f"""Imgine you are a professional career advisor, please comment on the below CV content.
        #                 Please ignore format issue at this moment as it is just the content.
        #                 Please summarise the advice and reponse within 200 words. 
        #                 CV: {cv_text} """
        #     # st.session_state.advice_text = generate_chat_completion(prompt).content
        #     st.session_state.advice_text = "####comment#####"

        #     st.subheader("AI Analysis & Recommendations")
        #     st.write(st.session_state.advice_text)

        if st.button("Generate Revised CV") or st.session_state.new_cv_text != "":
            prompt = f"""
                        Imagine you are a professional career advisor. 
                        Please help to revise the given CV, paying attention to the format. 
                        Generate the revised CV only, without any additional comments.
                        CV: {cv_text}
                    """
            st.session_state.new_cv_text = generate_chat_completion(prompt).content
            # st.session_state.new_cv_text = "New CV"

            # editable_cv = st.text_area("Edit CV", st.session_state.new_cv_text, height=600)
            editable_cv = st.session_state.new_cv_text
            pdf_data = generate_pdf(editable_cv)
            docx_io = create_docx(editable_cv)

            st.subheader("Preview")
            # st.markdown(editable_cv)
            st.image(convert_pdf_to_image(pdf_data), caption="CV Generated by CV Advisor")        
            
            col3, col4 = st.columns(2)
            
            with col3:
                st.download_button(label="Download PDF", data=pdf_data, file_name="Revised_CV.pdf", mime="application/pdf")
            with col4:
                st.download_button(label="Download Docx", data=docx_io, file_name="Revised_CV.docx", mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document")

        if st.button("Generate Cover Letter"):
            # Create a prompt for generating the cover letter
            cover_letter_prompt = f"""
                Write a cover letter for a job application based on the following details:
                Job Listing URL: {job_url}
                Key Skills: {skills}
                CV Content: {cv_text}

                Please make it professional and targeted for the job position.
            """
            cover_letter = generate_chat_completion(cover_letter_prompt).content
            cover_letter_pdf = generate_pdf(cover_letter)
            cover_letter_docx = create_docx(cover_letter)

            st.subheader("Preview")
            # st.markdown(editable_cv)
            st.image(convert_pdf_to_image(cover_letter_pdf), caption="Cover Letter Generated by CV Advisor")        
            st.download_button(label="Download Template", data=cover_letter_docx, file_name="Cover_Letter.docx", mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document")

    else:
        st.error("Please upload a CV before clicking Analyze.")
    

# Lower section in the second column
with col2:
    st.header("Chat Bot")
    messages_placeholder = st.container(height=550)
    
    # Initialize chat history
    if "messages" not in st.session_state:
        st.session_state.messages = []
        st.session_state.messages.append({"role": "assistant", 
                                          "content": 
                                          """
                                          Feel free to ask me any questions about your CV or share details about the job you're looking for!
                                          """
                                          })

    # Display chat messages from history on app rerun
    with messages_placeholder:
        for message in st.session_state.messages:
            with st.chat_message(message["role"]):
                st.markdown(message["content"])

    # React to user input
    if user_message := st.chat_input("What is up?"):
        # Add user message to chat history
        st.session_state.messages.append({"role": "user", "content": user_message})

        # Display user message in Chat Display
        with messages_placeholder:
            with st.chat_message("user"):
                st.markdown(user_message)

        # Generate AI response
            conversation_history_list = st.session_state.messages
        
        # Create a comprehensive prompt for the chatbot
        if uploaded_file:
            # Include additional information in the prompt
            additional_context = f"""
            Job Listing URL: {job_url}
            Key Skills: {skills}
            Relevant Experience: {experience}
            CV Content: {cv_text}
            """
            prompt = f"""
            Imagine you are a professional career advisor. 
            Please provide advice based on the following details:
            {additional_context}
            """

        else:
            prompt = f"""
                        Imgine you are a professional career advisor.
                    """

        response = f"{generate_chat_completion(prompt + user_message).content}"

        # Append "assistant" message to chat history
        st.session_state.messages.append({"role": "assistant", "content": response})
        # Display assistant response in chat message container
        with messages_placeholder:
            with st.chat_message("assistant"):
                st.markdown(response)
        

# Additional UI Elements
st.markdown("---")
st.write("Created by [Kyle Yeung](https://github.com/kyle-ycp)")